name: Publish better-auth-bili-basic
on:
  push:
    tags:
      - 'v*.*.*'
    paths:
      - package.json
  workflow_dispatch:

permissions:
  id-token: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 24.x
          registry-url: 'https://registry.npmjs.org'

      - uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Build better-auth-bili-basic
        run: |
          cd ${{ github.workspace }}
          bun run build

      - name: Publish better-auth-bili-basic
        run: |
          cd ${{ github.workspace }}
          npm publish --provenance --access public

      - run: bun x changelogithub
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
